FROM python:3.8

# We copy all file to leverage Docker cache
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r /app/requirements.txt

COPY . /app

WORKDIR /app

EXPOSE 5000
ENTRYPOINT [ "python3" ]

CMD [ "app.py" ]
